In [2]:
import numpy as np

In [ ]:
# first case

In [5]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = a+2
b

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
# a will not update
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 2nd case

In [8]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b = a[::2]
b

array([1, 3, 5, 7, 9])

In [10]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a[0] = 100
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [12]:
# b got changed
b

array([100,   3,   5,   7,   9])

In [15]:
# to check if memory shared
np.shares_memory(a,b)

True

In [17]:
len(b),len(a)

(5, 9)

In [18]:
b[1] = 1000
b

array([ 100, 1000,    5,    7,    9])

In [19]:
# since a and b shares same memory value changing to b will reflects to a
# b = a[::2]  - here b[1] means 3rd index 
a

array([ 100,    2, 1000,    4,    5,    6,    7,    8,    9])

In [22]:
c = b.reshape(5,1)
c

array([[ 100],
       [1000],
       [   5],
       [   7],
       [   9]])

In [20]:
np.shares_memory(a,b)

True

In [23]:
np.shares_memory(a,c)

True

In [24]:
np.shares_memory(c,b)

True

In [ ]:
# Shallow copy

In [25]:
a = np.arange(0,7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [27]:
b = a[::2]
b

array([0, 2, 4, 6])

In [28]:
c = a+2
c

array([2, 3, 4, 5, 6, 7, 8])

In [29]:
np.shares_memory(a,b)

True

In [30]:
# since a is getting updated or becoming new value therefore c will have new address and b is just values of stepsize of 2. 
np.shares_memory(a,c)

False

### DEEP COPY

In [31]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr1 = arr.copy()
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.shares_memory(arr,arr1)

False

In [ ]:
# exceptions in copy()

In [37]:
a = np.array([1,'m',[1,2,3,4,5]],dtype = 'object')
a

array([1, 'm', list([1, 2, 3, 4, 5])], dtype=object)

In [38]:
b = a.copy()
b

array([1, 'm', list([1, 2, 3, 4, 5])], dtype=object)

In [40]:
b[2][0] = 100
b

array([1, 'm', list([100, 2, 3, 4, 5])], dtype=object)

In [ ]:
# since b is the hard copy of a idealy it shouldnt change but it changed 

In [44]:
a

array([1, 'm', list([100, 2, 3, 4, 5])], dtype=object)

In [ ]:
# in object data type address of outer arrays are different for a and b,
# but address of element inside lists(nested list) are same(ref - numpy 4-(1:02)) 

In [ ]:
# for properly deep copy

In [45]:
import copy

In [46]:
c = copy.deepcopy(a)
c

array([1, 'm', list([100, 2, 3, 4, 5])], dtype=object)

In [47]:
a[2][2] = 1000
a

array([1, 'm', list([100, 2, 1000, 4, 5])], dtype=object)

In [48]:
# now c dosent changed , c is copied for each object that is for each level.
c

array([1, 'm', list([100, 2, 3, 4, 5])], dtype=object)

In [ ]:
# important
# copy() function copies just first level that is every element and
# deepcopy copies at every level that is each object at each element

In [ ]:
# whenever there is numpy object array we should use copy.deepcopy() instead of copy(). 

### Array Splitting and Merging

In [49]:
a = np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
# splits in three equal parts
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [52]:
# splits at index 2 and 5
np.split(a,[2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8])]

In [ ]:
# hsplit - horizontal split - column wise 
# vsplit - vertical split - row wise

In [53]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [55]:
np.hsplit(a,[3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [63]:
np.hsplit(a,[2,3])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [65]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [66]:
np.vsplit(a,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

### Stacking

In [70]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
# vstack - vertical stack - row
# hstack - horizontal stack - column

In [71]:
np.vstack([a,a,a])

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [72]:
np.vstack([a,[4,5,6,7],a])

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3]])

In [74]:
# it will convert all int data types to str data types and then stack.
np.vstack([a,['a','b','c','d'],a])

array([['0', '1', '2', '3'],
       ['a', 'b', 'c', 'd'],
       ['0', '1', '2', '3']], dtype='<U11')

In [73]:
np.vstack([a,[4,5,6,7,8],a])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 5

In [75]:
b = np.arange(4).reshape(4,1)
b

array([[0],
       [1],
       [2],
       [3]])

In [78]:
np.hstack([b,b])

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
np.shape(np.hstack([b,b]))

In [79]:
np.ndim(np.hstack([b,b]))

2

### CONCATENATE

In [84]:
a = np.array([0,1,2])
b = np.array([3,4,5])

In [85]:
a

array([0, 1, 2])

In [82]:
b

array([3, 4, 5])

In [86]:
np.concatenate([a,b],axis=0)

array([0, 1, 2, 3, 4, 5])

In [87]:
a = np.array([[0,1,2]])
b = np.array([[3,4,5]])

In [88]:
# for output to be 2D input also need to be 2D. 
np.concatenate([a,b],axis=0)

array([[0, 1, 2],
       [3, 4, 5]])

In [90]:
a = np.array([[0,1,2]]).reshape(3,1)
b = np.array([[3,4,5]]).reshape(3,1)

In [92]:
np.concatenate([a,b],axis=1)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [94]:
# None conversts 2D to 1D array
np.concatenate([a,b],axis=None)

array([0, 1, 2, 3, 4, 5])

In [95]:
# reshape(2,3,4) - 2-parts, 3-row, 4-columns
a = np.arange(0,24).reshape(2,3,4)  #0,1,2 its an reference to original index - (see - numpy 4 - 02:13)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [98]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [97]:
np.transpose(a,[1,0,2])

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [99]:
np.transpose(a,[0,2,1])

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [ ]:
# assignment

In [105]:
#4
arr = np.arange(16).reshape(4,4)  
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [106]:
print(np.split(arr,4))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [107]:
# 5
arr = np.array([1,2,3,0,-2,4])
arr

array([ 1,  2,  3,  0, -2,  4])

In [108]:
arr1 = arr[:]
arr1

array([ 1,  2,  3,  0, -2,  4])

In [109]:
np.shares_memory(arr,arr1)

True

In [110]:
arr[2] = 100
arr

array([  1,   2, 100,   0,  -2,   4])

In [111]:
arr1

array([  1,   2, 100,   0,  -2,   4])

In [112]:
#6
X = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
mask = np.array([1, 0, 1, 0], dtype=bool)


In [117]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
print(row[:])

[0 1 2]


In [114]:
print([row[:, np.newaxis]])

[array([[0],
       [1],
       [2]])]


In [115]:
print(X[row[:, np.newaxis]])

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]


In [116]:
print(X[row[:, np.newaxis], mask])

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [3]:
#1
#approach 1
mat = np.arange(1,7).reshape(3,2)
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
mat.shape

(3, 2)

In [6]:
m,n = mat.shape
arr = np.zeros([(m+2),(n+2)])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
arr[1:-1,1:-1]

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [61]:
arr[1:-1,1:-1] = mat

In [62]:
print(arr)

[[0. 0. 0. 0.]
 [0. 1. 2. 0.]
 [0. 3. 4. 0.]
 [0. 5. 6. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#approach 2

In [19]:
m,n = a.shape 
m,n

(3, 2)

In [22]:
h_z = n*[0]

In [27]:
newar = np.vstack([h_z,mat,h_z])
newar

array([[0, 0],
       [1, 2],
       [3, 4],
       [5, 6],
       [0, 0]])

In [73]:
m,n = newar.shape
m

5

In [74]:
v_z = np.array(m*[0]).reshape(m,1)

In [75]:
v_z

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [76]:
newarr = np.hstack([v_z,newar,v_z])
print(newarr)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 5 6 0]
 [0 0 0 0]]


In [8]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
np.pad(mat,(2,2))

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 0, 0],
       [0, 0, 3, 4, 0, 0],
       [0, 0, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [10]:
np.pad(mat,(1,1))

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 5, 6, 0],
       [0, 0, 0, 0]])

In [12]:
np.pad(mat,(3))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 0, 0, 0],
       [0, 0, 0, 3, 4, 0, 0, 0],
       [0, 0, 0, 5, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [83]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [88]:
n,m = mat.shape
h_z = [0]*m
arr = np.vstack([h_z,mat,h_z])
n,m = arr.shape
v_z = np.array([0]*n).reshape(5,1)
arr = np.hstack([v_z,arr,v_z])
print(arr)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 5 6 0]
 [0 0 0 0]]


In [90]:
# approach 3
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
arr = np.pad(mat,1)
print(arr)

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 5 6 0]
 [0 0 0 0]]


In [ ]:
# homework

In [118]:
# 1
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
arr[:,0]

array([1, 4, 7])

In [121]:
np.hstack((arr, arr[:, 0]))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [122]:
np.ndim(arr[:, 0])

1

In [126]:
# DOUBT

In [ ]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [125]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
arr[:,0]

array([1, 4, 7])

In [123]:
arr[:,[0]]

array([[1],
       [4],
       [7]])

In [128]:
arr[:, 0]

array([1, 4, 7])

In [129]:
#6
a = np.arange(9).reshape(3,3,1)
a

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [130]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [133]:
a = a.squeeze(axis=2) 
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [132]:
b = np.expand_dims(b, axis=2)  
b

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])