In [5]:
import numpy as np

In [2]:
data = np.loadtxt('fit.txt','str')

In [3]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [5]:
data[data == 'Happy']

array(['Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy'], dtype='<U10')

In [18]:
#assigning column name

date,step_count,mood,calorie_burned,hour_of_sleep,activity_status = data.T

In [22]:
#converting stepcount to int

step_count = step_count.astype('int')

In [24]:
# finding step counts where mood is sad.

step_count[mood=='Sad']

array([6041,   25, 5461, 4545, 4340, 1230,   61, 1258, 3148, 4687, 3519,
       1580, 2822,  181, 6676, 3721, 1648,  799, 1696,  221, 4061,  651,
        753,  518,  177,   36,  299,  702,  133])

In [ ]:
# axis wise aggregations

In [9]:
m = np.arange(12).reshape(3,-1)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
np.sum(m,axis=0)

array([12, 15, 18, 21])

In [11]:
np.sum(m,axis=1)

array([ 6, 22, 38])

In [26]:
#days on which step count is greater or equal to four thousand

date[step_count>=4000]

array(['06-10-2017', '07-10-2017', '09-10-2017', '10-10-2017',
       '11-10-2017', '12-10-2017', '17-10-2017', '18-10-2017',
       '24-10-2017', '26-10-2017', '31-10-2017', '01-11-2017',
       '02-11-2017', '06-11-2017', '07-11-2017', '08-11-2017',
       '09-11-2017', '10-11-2017', '11-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '20-11-2017', '21-11-2017',
       '22-11-2017', '23-11-2017', '24-11-2017', '29-11-2017',
       '03-12-2017', '05-12-2017', '12-12-2017', '14-12-2017',
       '18-12-2017', '20-12-2017', '22-12-2017', '26-12-2017',
       '27-12-2017', '28-12-2017'], dtype='<U10')

In [29]:
# gives unique value in mood and their total counts  

np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([40, 27, 29], dtype=int64))

In [27]:
#how was the mood where step count >= 4000

mood[step_count>=4000]

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Happy',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Sad',
       'Happy', 'Neutral', 'Happy'], dtype='<U10')

In [30]:
#what was the total counts of mood where step count >= 4000


np.unique(mood[step_count>=4000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([22,  9,  7], dtype=int64))

In [ ]:
# logical operators

In [12]:
a = np.array([4,3,2,1])
b = np.array([1,2,3,4])

In [13]:
np.any(a>b)

True

In [14]:
np.all(a>b)

False

In [15]:
# where returs index
np.where(a>b)

(array([0, 1], dtype=int64),)

In [17]:
# assighning value for true and false conditions
np.where(a>b,'true','false')

array(['true', 'true', 'false', 'false'], dtype='<U5')

### Arg max and Arg min

In [31]:
# it is an 1D array
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [32]:
step_count.max()

7422

In [33]:
#returns the index of max value
step_count.argmax()

69

In [3]:
import numpy as np
a = np.array([1,5,6,8,9,7,2,11,3,6])
a.argmax()

7

In [34]:
#what is the mood where I walked the most
mood[step_count == step_count.max()]

array(['Happy'], dtype='<U10')

In [35]:
mood[step_count.argmax()]

'Happy'

In [38]:
a = np.arange(2,14).reshape(3,-1)

In [39]:
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [40]:
# 2D array first gets flatten and then search for max value index 
np.argmax(a)

11

In [ ]:
#returning max row/column wise

In [42]:
# for column wise
np.max(a,axis=0)

array([10, 11, 12, 13])

In [43]:
# for row wise
np.max(a,axis=1)

array([ 5,  9, 13])

In [ ]:
#returning max index row/column wise

In [46]:
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [44]:
np.argmax(a,axis=0)

array([2, 2, 2, 2], dtype=int64)

In [45]:
np.argmax(a,axis=1)

array([3, 3, 3], dtype=int64)

### SUM

In [51]:
arr = np.arange(10,0,-1)
arr = arr.reshape(5,2)

In [52]:
arr

array([[10,  9],
       [ 8,  7],
       [ 6,  5],
       [ 4,  3],
       [ 2,  1]])

In [53]:
np.sum(arr,axis=0)

array([30, 25])

In [54]:
np.sum(arr,axis=1)

array([19, 15, 11,  7,  3])

### SORTING

In [70]:
a = np.array([10,9,8,7,6,5])

In [71]:
np.sort(a)


array([ 5,  6,  7,  8,  9, 10])

In [72]:
a

array([10,  9,  8,  7,  6,  5])

In [73]:
#argsort first sort in asc then it gives the index
np.argsort(a)

array([5, 4, 3, 2, 1, 0], dtype=int64)

### Matrix Multiplication

In [77]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [78]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [76]:
a*b

array([0., 1., 2., 3., 4.])

In [81]:
a = np.arange(12).reshape(3,-1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
a.shape

(3, 4)

In [89]:
b = np.arange(2,14).reshape(3,-1).T
b

array([[ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12],
       [ 5,  9, 13]])

In [90]:
b.shape

(4, 3)

In [91]:
np.dot(a,b)

array([[ 26,  50,  74],
       [ 82, 170, 258],
       [138, 290, 442]])

In [92]:
a@b

array([[ 26,  50,  74],
       [ 82, 170, 258],
       [138, 290, 442]])

In [93]:
np.matmul(a,b)

array([[ 26,  50,  74],
       [ 82, 170, 258],
       [138, 290, 442]])

In [95]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [96]:
#it is only specific for matrix multiplication
np.matmul(a,2)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [97]:
# it is for all kind of multiplications
np.dot(a,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [6]:
birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])

In [7]:
age

array([5.5, 6. , 3.5, 1.5, 3. , 4. , 3.5, 2. , 5.5, 6. ])

In [9]:
[age>3]

[array([ True,  True,  True, False, False,  True,  True, False,  True,
         True])]