In [210]:
import numpy as np

In [2]:
a = [1,2,3,4,5]

In [3]:
b = np.array(a)

In [4]:
type(a),type(b)

(list, numpy.ndarray)

In [11]:
a**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [6]:
b**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [14]:
b

array([1, 2, 3, 4, 5])

In [12]:
# to check for dimension of array
b.ndim

1

In [13]:
# to check for shape of array
b.shape

(5,)

In [16]:
c = [[1,2],[3,4]]

In [17]:
d = np.array(c)

In [18]:
c

[[1, 2], [3, 4]]

In [19]:
d

array([[1, 2],
       [3, 4]])

In [23]:
d.ndim

2

In [25]:
d.shape

(2, 2)

In [27]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [30]:
arr1.ndim,arr1.shape

(1, (5,))

In [31]:
arr2 = np.array([[1,2,3,4,5]])
arr2

array([[1, 2, 3, 4, 5]])

In [32]:
arr2.ndim,arr2.shape

(2, (1, 5))

In [34]:
arr3 = np.array([[1],[2],[3],[4],[5]])

In [35]:
arr3.ndim,arr3.shape

(2, (5, 1))

In [36]:
list1 = [[1],[2],[3],[4],[5]]

In [37]:
list1

[[1], [2], [3], [4], [5]]

In [38]:
for i in list1:
    print(i)

[1]
[2]
[3]
[4]
[5]


In [41]:
for i in list1:
    for j in i:
        print(j)

1
2
3
4
5


In [43]:
list2 = [[1,2,3,4,5]]

In [44]:
for i in list2:
    print(i)

[1, 2, 3, 4, 5]


In [45]:
for i in list2:
    for j in i:
        print(j)

1
2
3
4
5


In [ ]:
# range Vs arange

In [48]:
a = range(1,10,2)
for i in a:
    print(i)

1
3
5
7
9


In [51]:
a = np.arange(1,10,1.5)
for i in a:
    print(i)

1.0
2.5
4.0
5.5
7.0
8.5


In [52]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
a[[1,-1,-5]]

array([ 2, 11,  7])

In [57]:
a>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [58]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11])

In [59]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
a.astype('float64')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
# calculating the NPS of survey - (%Promoter - %Detractors)

In [63]:
score = np.loadtxt('survey.txt')

In [64]:
score

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [65]:
score.shape

(1167,)

In [66]:
score.ndim

1

In [ ]:
#Promoters

In [68]:
promoters = score[score>=9]

In [70]:
promoters.shape

(609,)

In [ ]:
# % of promoters

In [78]:
promo_percent = promoters.shape[0]/score.shape[0]

In [79]:
promo_percent

0.5218508997429306

In [ ]:
#Detractors

In [74]:
detractors = score[score<=6]

In [75]:
detractors.shape

(332,)

In [ ]:
# % of detractors

In [80]:
det_percent = detractors.shape[0]/score.shape[0]

In [81]:
det_percent

0.28449014567266495

In [97]:
nps = ((promo_percent - det_percent)*100)
nps  = round(nps,2)
nps

23.74

In [98]:
a = [1,2,3,4,5]
b = [7,8,9]
a[3:] = b[::-2]
a

[1, 2, 3, 9, 7]

In [104]:
data.ndim

2

In [105]:
data.shape

(96, 6)

In [106]:
data.shape[0]

96

In [107]:
data.shape[1]

6

In [109]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [112]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
# puting '-1' will automatically adjust to give correct shape
a.reshape(4,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
a.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [116]:
a = a.reshape(8,-1)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [118]:
# 2nd row 2nd col
a[2][1]

5

In [119]:
# 3rd row 2nd col
a[3,1]

7

In [ ]:
# multiple element selection

In [124]:
#incorrect - 
a[[3,1],[2,1]]

IndexError: index 2 is out of bounds for axis 1 with size 2

In [125]:
# multiple element selection
#correct - [2nd row,3rd row] [1st element 1st element]
a[[2,3],[1,1]]

array([5, 7])

In [ ]:
# Transpose

In [120]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [121]:
a.shape

(8, 2)

In [123]:
a.T.shape

(2, 8)

In [ ]:
# slicing columns

In [126]:
s = np.arange(12).reshape(3,-1)
s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
s[:,0]

array([0, 4, 8])

In [129]:
s[:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [135]:
s.T[2:].T

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
# Fitbit data

In [136]:
data = np.loadtxt('fit.txt',dtype = 'str') 

In [137]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [ ]:
# Approach 1

In [138]:
# to select only dates column
data[:,0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [139]:
# to select step count column
data[:,1]

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [140]:
step_count = data[:,1].astype('int')
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [143]:
#Approach 2

In [144]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [145]:
# using multiple assigning

In [154]:
a,b = [[1],
       [2]]

In [155]:
a

[1]

In [156]:
b

[2]

In [146]:
date,step_count,mood,calorie_burned,hour_of_sleep,activity_status = data.T

In [147]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [149]:
activity_status

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

In [157]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [160]:
step_count = step_count.astype('int')
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [141]:
# agg func
np.mean(step_count)

2935.9375

In [142]:
np.max(step_count)

7422

In [161]:
f = np.array([100,200,600,300,500,800,900,700])

In [163]:
f[[0,3,5]]

array([100, 300, 800])

In [164]:
f.ndim

1

In [166]:
f[1,2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [171]:
g = np.array([[[100,200,600,300,500,800,900,700],[50,60,10,30,90]]])

C:\Users\SOURABH\AppData\Local\Temp\ipykernel_19336\670312111.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  g = np.array([[[100,200,600,300,500,800,900,700],[50,60,10,30,90]]])


In [173]:
g

array([[list([100, 200, 600, 300, 500, 800, 900, 700]),
        list([50, 60, 10, 30, 90])]], dtype=object)

In [187]:
g[:]

array([[list([100, 200, 600, 300, 500, 800, 900, 700]),
        list([50, 60, 10, 30, 90])]], dtype=object)

In [172]:
g.ndim

2

In [178]:
g[0,0]

[100, 200, 600, 300, 500, 800, 900, 700]

In [176]:
g[0,1]

[50, 60, 10, 30, 90]

In [181]:
data[2]

array(['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'], dtype='<U10')

In [179]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [182]:
# 5
a = np.array([[34, 28,55], [8, 56, 3], [77, 87, 19]])
print(a.transpose()[-2,-2])

56


In [184]:
# 3
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x.flatten())

[16 81 33  5  6  1]


In [ ]:
#2 Code Snippet a:

x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1]) 

In [191]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print( v[:]) 

[200 300 400]


In [192]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print( v[:,None]) 

[[200]
 [300]
 [400]]


In [193]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])) 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [194]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1]) 

1.0


In [ ]:
# Code Snippet b:

In [ ]:
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
print((p + q)[1][1]) 

In [199]:
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
print((p + q))

[[10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
# 1

In [200]:
arr = 2 * np.arange(0,2,0.5)
if arr <= 0.6:
    print("condition satisfies")
else:
    print("condition doesn't satisfy")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [202]:
np.arange(0,2,0.5)

array([0. , 0.5, 1. , 1.5])

In [201]:
arr

array([0., 1., 2., 3.])

In [203]:
arr = 2 * np.arange(0,2,0.5)
if arr.any() <= 0.6:
    print("condition satisfies")
else:
    print("condition doesn't satisfy")

condition doesn't satisfy


In [204]:
arr = 2 * np.arange(0,2,0.5)
if arr.all() <= 0.6:
    print("condition satisfies")
else:
    print("condition doesn't satisfy")

condition satisfies


In [ ]:
# HOMEWORK

In [212]:
#5 input
a = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])

In [ ]:
# output
[[7 4 1]
 [8 5 2]
 [9 6 3]]

In [213]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [215]:
a.T[::-1]

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [217]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [216]:
a[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [218]:
# solution
a[::-1].T

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [ ]:
#4

In [228]:
a = [[0, 1, 2], 
     [3, 4, 5], 
     [6, 7, 8]]

In [229]:
# correct for list
b = [i[::-1] for i in a]

In [234]:
a =np.array([[0, 1, 2], 
     [3, 4, 5], 
     [6, 7, 8]])

In [235]:
# for numpy array
a[::,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [236]:
#3
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6  8  7 28 56 19]]


In [240]:
#2

In [246]:
b = np.array([[3, 3, 8, 2, 2, 1, 3, 9, 2, 3],
     [7, 9, 9, 7, 2, 2, 2, 7, 0, 5],
     [5, 1, 1, 9, 4, 7, 0, 4, 4, 8],
     [1, 3, 7, 2, 1, 1, 2, 0, 4, 3],
     [6, 4, 4, 4, 2, 5, 7, 3, 9, 6]])


In [ ]:
# output
[[0 4 3]
 [4 4 8]
 [7 0 5]]

In [250]:
b[1:4,-3:]

array([[7, 0, 5],
       [4, 4, 8],
       [0, 4, 3]])

In [253]:
#1
a = np.arange(10)

In [254]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [266]:
mask = a[a%2==0 ]

In [271]:
mask = mask[mask>4]

In [272]:
a[mask]

array([6, 8])

In [268]:
mask = a.all[a%2==0 & a>4]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [256]:
a[mask]

array([0, 2, 4, 6, 8])

In [274]:
b = np.array([8,12,16,20])

In [279]:
b

array([ 8, 12, 16, 20])

In [280]:
mask = b[b%2==0 ]

In [281]:
mask = mask[mask>4]

In [282]:
mask

array([ 8, 12, 16, 20])

In [283]:
mask == b

array([ True,  True,  True,  True])

In [285]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [287]:
np.all((a>4) & (a%2==0))

False

In [288]:
np.all((b>4) & (b%2==0))

True

In [ ]:
# test question 1

In [290]:
def func1():
    print('third')
    func2()
    

In [291]:
def func2():
    print('second')
    func3()

In [292]:
def func3():
    print('first')
    

In [293]:
func1()

third
second
first


In [ ]:
# test question 2

In [300]:
people = [('Alice',25),('BOB',32),('Charlie',20),('David',35)]

oldest_name = ''
oldest_age = 0

for name,age in people:
    if age>oldest_age:
        oldest_name = name
        oldest_age = age
print('the oldest person is',oldest_name)        

the oldest person is David


In [301]:
def maxOnes(arr):
    
  #write code
    max_count = 0
    row = -1
    for i in range(len(arr)):
        count = 0
        for j in range(len(arr[0])):
            if arr[i][j] == 1:
                count += 1
        if count> max_count:
            max_count = count
            row = i
    return row     

In [303]:
maxOnes([[0,1,1,1],[0,0,1,1],[0,0,1,1],[1,1,0,0]])

0